# -*- coding: utf-8 -*-
"""Processing image daata for deep learning.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1YEQi5d4Vj880DWB7MDJclSRDtQb2tZ_M
"""

#getting an image using web get
!wget "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQrjpZDQMz0rMUVKZwI0vOAyljJz5mh4xdHiStca8BN-GqSc7ey08j2-K9hjA&s"

#libraries that we will be using for image processing
import matplotlib.image as mpimage
import matplotlib.pyplot as plt

#loading an image through matplotlib.image module

img = mpimage.imread("/content/images?q=tbn:ANd9GcQrjpZDQMz0rMUVKZwI0vOAyljJz5mh4xdHiStca8BN-GqSc7ey08j2-K9hjA&s")

type(img)

print(img.shape)

print(img)

#displaying this imag as numpy array

img_plot = plt.imshow(img)
plt.show()

#Resizing the image using pillow library

from PIL import Image

img = Image.open("/content/images?q=tbn:ANd9GcQrjpZDQMz0rMUVKZwI0vOAyljJz5mh4xdHiStca8BN-GqSc7ey08j2-K9hjA&s")
img_resized = img.resize((200,200))

img_resized.save("dog_image_resized.jpg")

img_res = mpimage.imread("/content/dog_image_resized.jpg")
img_res_plot = plt.imshow(img_res)
plt.show()

print(img_res.shape)

"""**Convert RGB images to Grayscale image using OpenCV**"""

import cv2

img = cv2.imread("/content/images?q=tbn:ANd9GcQrjpZDQMz0rMUVKZwI0vOAyljJz5mh4xdHiStca8BN-GqSc7ey08j2-K9hjA&s")

type(img)

img.shape

grayscale_image = cv2.cvtColor(img, cv2.COLOR_RGB2GRAY)

type(grayscale_image)

grayscale_image.shape

from google.colab.patches import cv2_imshow

cv2_imshow(grayscale_image)

#saving the grayscale_image
cv2.imwrite("dog_grayscale_image.jpg" , grayscale_image)